### ISSUE TITLE
when there are no examples provided, the parsing results are inaccurate

### ISSUE THREAD

**Issue by aixiamomo** [eyurtsev/kor#202] opened 2023-08-08 06:04 UTC
```
res = chain.run("Please help me search for all the tender notices of big data companies on record until the day before yesterday.")
```

{'data': {}, 'raw': '<json>{\n  "industry": "big data",\n  "type": "tender",\n  "deadline": "2023-08-05"\n}</json>', 'errors': [ParseError('The LLM has returned structured data which does not match the expected schema. Providing additional examples may help improve the parse.')], 
'validated_data': {}}

the top-level object is missing

**Comment by eyurtsev** [comment] 2023-08-08 13:27
Hi @aixiamomo -- this is not a bug in kor, but a limitation of the LLM that you're using. Most LLMs can't parse structured data well without having some examples. 

See guidelines here: https://eyurtsev.github.io/kor/guidelines.html

Closing as this is not a bug that needs to be fixed.

**Closed by eyurtsev** 2023-08-08 13:27 UTC

**Comment by aixiamomo** [comment] 2023-08-09 06:17
> Hi @aixiamomo -- this is not a bug in kor, but a limitation of the LLM that you're using. Most LLMs can't parse structured data well without having some examples.
> 
> See guidelines here: https://eyurtsev.github.io/kor/guidelines.html
> 
> Closing as this is not a bug that needs to be fixed.

Thank you, I understand. Meanwhile, I have used the following code to ensure that the llms can produce output in the desired format even without examples:

```python
from kor import prompts, examples

def _generate_examples(node):
    examples_list = examples.generate_examples(node)
    return examples_list if examples_list else [("", {node.id: {}})]


prompts.generate_examples = _generate_examples
```
