### ISSUE TITLE
:grey_question: How to "pipe" around Kor and langchain :sloth: 

### ISSUE THREAD

**Issue by adriens** [eyurtsev/kor#203] opened 2023-08-09 08:02 UTC
Hi, langchain has recently supported the `|` operator:

```python
chain = prompt | model
```

... and as for now I've started to use kor with the following syntax (very good results btw) : 

```python
chain = create_extraction_chain(llm, schema)
```

I wonder how I could use pipes to do the same on langchain ?

I find the `|` syntax very elegant and concise and it seems like it gets a lot of traction so I ask.

Thank you in advance for your help, I've searched if the question had already asked but it seems like it hasn't.

**Comment by eyurtsev** [comment] 2023-08-10 17:25
It'll be helpful to know what you're trying to do with the `|` symbol.

`create_extraction_chain` assembles the chain (and whether it uses `|` or some other method is an implementation detail that's hidden from the user); i.e., I may at some point rewrite it using Langchain Runnables (the building blocks for `|`), but users will not be aware of this

**Comment by adriens** [comment] 2023-08-11 03:10
So I should stick with traditional notation and not necessarly switch to the pipe syntax ?

**Comment by eyurtsev** [comment] 2023-08-15 14:39
If you're making custom chains using langchain runnables, the pipe syntax is very useful as it provides support for sync/async and batch as well as streaming variants out of the box.

If using an existing chain like the one in Kor and it's working then there's no advantage in swapping to the pipe syntax (as a user).

`Kor` internally will probably benefit from leveraging runnables more, so I will eventually update the internal code to use it :)

**Comment by eyurtsev** [comment] 2023-09-06 14:13
Closing issue for now since this is not a bug :)

**Closed by eyurtsev** 2023-09-06 14:13 UTC
